export const travels = [
  { name: 'Puerto vallarta - 1' },
  { name: 'Cancún - 2' },
  { name: 'Guayabitos - 3' },
  { name: 'Guadalajara - 4' },
  { name: 'Tequila - 5' },
  { name: 'Ciudad de México - 6' },
  { name: 'Guanajuato - 7' },
  { name: 'Yucatán - 8' },
  { name: 'Acapulco - 9' },
  { name: 'Querétaro - 10' },
  { name: 'Quintana Roo - 11' },
  { name: 'Puerto vallarta - 12' },
  { name: 'Cancún - 13' },
  { name: 'Guayabitos - 14' },
  { name: 'Guadalajara - 15' },
  { name: 'Tequila - 16' },
  { name: 'Ciudad de México - 17' },
  { name: 'Guanajuato - 18' },
  { name: 'Yucatán - 19' },
  { name: 'Acapulco - 20' },
  { name: 'Querétaro - 21' },
  { name: 'Quintana Roo - 22' },
  { name: 'Puerto vallarta - 23' },
  { name: 'Cancún - 24' },
  { name: 'Guayabitos - 25' },
  { name: 'Guadalajara - 26' },
  { name: 'Tequila - 27' },
  { name: 'Ciudad de México - 28' },
  { name: 'Guanajuato - 29' },
  { name: 'Yucatán - 30' },
  { name: 'Acapulco - 31' },
  { name: 'Querétaro - 32' },
  { name: 'Quintana Roo - 33' },
  { name: 'Puerto vallarta - 34' },
  { name: 'Cancún - 35' },
  { name: 'Guayabitos - 36' },
  { name: 'Guadalajara - 37' },
  { name: 'Tequila - 38' },
  { name: 'Ciudad de México - 39' },
  { name: 'Guanajuato - 40' },
  { name: 'Yucatán - 41' },
  { name: 'Acapulco - 42' },
  { name: 'Querétaro - 43' },
  { name: 'Quintana Roo - 44' }
]
